services:
  vendor-server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8001:8001"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://buvvadb:buvvA%406@host.docker.internal:5432/onfood
      - SQL_ECHO=false
      - STATIC_IMAGES_DIR=/app/static/images
    volumes:
      - ../onfoodserver/app/static/images:/app/static/images:ro
      - ./uploads:/app/uploads
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db-manager:
    build:
      context: ./db-manager
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=postgresql://buvvadb:buvvA%406@host.docker.internal:5432/onfood
      - PORT=8002
    extra_hosts:
      - "host.docker.internal:host-gateway"
