"""init_all_tables

Revision ID: 61b3cdd89624
Revises: 
Create Date: 2026-07-10 04:06:08.742282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61b3cdd89624'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faq_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kitchen_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_prep_buffer_minutes', sa.Integer(), nullable=False),
    sa.Column('max_concurrent_orders', sa.Integer(), nullable=False),
    sa.Column('is_accepting_orders', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faq_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['faq_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('support_tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', name='ticket_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('menu_item_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('menu_items', sa.Column('original_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('menu_items', sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('menu_items', sa.Column('category_id', sa.UUID(), nullable=True))
    op.add_column('menu_items', sa.Column('is_available', sa.Boolean(), nullable=True))
    op.add_column('menu_items', sa.Column('preparation_time_minutes', sa.Integer(), nullable=True))
    
    # Populate existing rows
    op.execute("UPDATE menu_items SET is_available = true WHERE is_available IS NULL")
    op.execute("UPDATE menu_items SET preparation_time_minutes = 10 WHERE preparation_time_minutes IS NULL")
    
    # Alter to not null
    op.alter_column('menu_items', 'is_available', nullable=False)
    op.alter_column('menu_items', 'preparation_time_minutes', nullable=False)
    
    op.create_foreign_key(None, 'menu_items', 'categories', ['category_id'], ['id'])
    op.drop_column('menu_items', 'category')
    op.add_column('orders', sa.Column('pickup_number', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('pickup_date', sa.Date(), nullable=True))
    op.add_column('orders', sa.Column('estimated_ready_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('actual_ready_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'notes')
    op.drop_column('orders', 'actual_ready_at')
    op.drop_column('orders', 'estimated_ready_at')
    op.drop_column('orders', 'pickup_date')
    op.drop_column('orders', 'pickup_number')
    op.add_column('menu_items', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'menu_items', type_='foreignkey')
    op.drop_column('menu_items', 'preparation_time_minutes')
    op.drop_column('menu_items', 'is_available')
    op.drop_column('menu_items', 'category_id')
    op.drop_column('menu_items', 'discount_percent')
    op.drop_column('menu_items', 'original_price')
    op.drop_table('cart_items')
    op.drop_table('support_tickets')
    op.drop_table('faq_items')
    op.drop_table('kitchen_settings')
    op.drop_table('faq_categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
