"""add_scheduling

Revision ID: d53b2174aa71
Revises: 61b3cdd89624
Create Date: 2026-07-10 21:35:49.362338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd53b2174aa71'
down_revision: Union[str, Sequence[str], None] = '61b3cdd89624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_slots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('max_orders', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('orders', sa.Column('scheduled_date', sa.Date(), nullable=True))
    op.add_column('orders', sa.Column('scheduled_slot_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'orders', 'time_slots', ['scheduled_slot_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'scheduled_slot_id')
    op.drop_column('orders', 'scheduled_date')
    op.drop_table('time_slots')
    # ### end Alembic commands ###
